### ISSUE TITLE
Add a GeoJson file.

### ISSUE THREAD

**Issue by kobiluria** [kobiluria/MoneyMap#15]
add a function to export the DB into a geojson file. 
me and nir have a few idea's using this file.

**Comment by kobiluria** [comment]
@niryariv i'm adding a geojson file which is the dump of the db as discussed. i will probably try to uniquely describe only muni's in this file in the next few days. we should create other ones elsewhere. thanks for time yesterday.

**Comment by niryariv** [comment]
@kobiluria awesome, thanks!
