### ISSUE TITLE
Query The Open budget API

### ISSUE THREAD

**Issue by kobiluria** [kobiluria/MoneyMap#2]
@pwalsh 

i Wanted to re query the API and create an mongodb database from new queries to the API , i know i can  run it local on my machine but
 the right way of doing it will be pulling the data from the open - budget api.
What is the current API URL and the endpoints?

**Comment by pwalsh** [comment]
Hey @kobiluria 

For now the API is available at:

http://staging.openmuni.org.il/api/v1/

And specifically, Entities are at:

http://staging.openmuni.org.il/api/v1/entities/

The base URL will change in the next months, but that is it.

**Comment by kobiluria** [comment]
Querying pretty well now, 
I have a few questions for a different issue.
