### ISSUE TITLE
Add a Date Time Mongo object to each entity

### ISSUE THREAD

**Issue by kobiluria** [kobiluria/MoneyMap#3]
- we need to add a Date Time object in order to query entities polygons by Date

**Comment by pwalsh** [comment]
You might want to do something like we did in Open Budgets, where some model objects have a period_start field, and some have both period_start and period_end.

Here are the mixins we use to declare the models there:

https://github.com/openbudgets/openbudgets/blob/develop/openbudgets/commons/mixins/models.py#L105

https://github.com/openbudgets/openbudgets/blob/develop/openbudgets/commons/mixins/models.py#L125

As a general approach, objects that only have a period_start property are considered to apply until the next object in the table with a future period_start, whereas objects with both period_start and period_end are applicable for the explicit period they define.

For the maps here, you _probably_ just want something like the first scenario. That would support an example like, you have a tel aviv polygon from 1995, and a new one was published in 2001. The 1995 would "apply" for the whole period until the next object, from 2001.

**Comment by kobiluria** [comment]
Hi, sorry didn't respond yet to the previous mail i was on the way back home. 
I'm here now until August so hopefully i will be able to get down to you sometime. 

I like the first idea, I think I’m going for pure Mongo objects , since i want to use the geojson metrics for area calculations so i decided to diverge from MVC and use standard monogodb JavaScript requests, 

I think we will use the first idea, since a map is updated like once a month the only information needed is when the map was obtained and not the period ( unlike a budget which has a very meaningful reason why to store a period) storing a period for a map might not be correct since the map could of change during that period. 

so i will store a obtain_date for each document.

i will try to update issues and fix's more frequently now that i'm here , it helps me keep track, and i might work on this project an hour a day during the next two months. so hopefully it will start getting a shape , and a proper documentations soon. :)

**Comment by pwalsh** [comment]
Nice one. I saw you moved to express.js which I think is the best decision for what you are doing.
