### ISSUE TITLE
Update the looks of the front page

### ISSUE THREAD

**Issue by kobiluria** [kobiluria/MoneyMap#47]
We will use mkdocs(python) for converting markdown Readme files into a HTML front page.

**Comment by pwalsh** [comment]
@kobiluria hi! Is there a live demo anywhere?

**Comment by kobiluria** [comment]
@pwalsh yes there is a small dev server , trying new things. 
its deployed using Red Hat - Open Shift. 
With a MongoDB instance. 

http://api-moneymap.rhcloud.com/

still didn't get everything up and running. and still working on adding Geo-spatial queries
so slowly and surly. 

I use openbudgets unique ids i.e see : 
1. **The Entity with all proprieties** : http://api-moneymap.rhcloud.com/api/entities/7276a92d-c13e-47b8-a320-342a1abadeaf 
2. **The GeoJSON** : http://api-moneymap.rhcloud.com/api/maps/7276a92d-c13e-47b8-a320-342a1abadeaf

3.*_The GUI MAP *_ : http://api-moneymap.rhcloud.com/gui/maps/7276a92d-c13e-47b8-a320-342a1abadeaf

**Comment by pwalsh** [comment]
Nice work man.
